# Generated by Django 5.2.7 on 2025-12-10 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrowdStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('LIGHT', 'Not Crowded'), ('MOD', 'Moderately Crowded'), ('HEAVY', 'Very Crowded')], default='LIGHT', max_length=10)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.building')),
            ],
            options={
                'verbose_name_plural': 'Crowd Status',
            },
        ),
    ]
